version: "3.8"

services:
  habridge:
    image: ghcr.io/linuxserver/habridge
    container_name: habridge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - SEC_KEY=${RANDOM}
      - TZ=America/Toronto
    restart: unless-stopped
